language: android
android:
  components:
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_script:
- chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
before_install:
- openssl aes-256-cbc -K $encrypted_04bcdd73bf31_key -iv $encrypted_04bcdd73bf31_iv
  -in Flip.jks.enc -out Flip.jks -d
- gem install fir-cli
script:
- "./gradlew assembleRelease"

after_success:
- fir p mobile/build/outputs/apk/release/mobile-release.apk -T $FIR_TOKEN -c $TRAVIS_COMMIT_MESSAGE